// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh-FBUBAVckh4AfMpBjhSaeLSOF2wUXwU',
    appId: '1:1001314955992:web:ab661824d31721f3881dad',
    messagingSenderId: '1001314955992',
    projectId: 'sgpjtjcn-65e0a',
    authDomain: 'sgpjtjcn-65e0a.firebaseapp.com',
    storageBucket: 'sgpjtjcn-65e0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRUiItBwjSc-gI6X8Rp-Fh8iO5IgrbzQ',
    appId: '1:1001314955992:android:641057f158c6931c881dad',
    messagingSenderId: '1001314955992',
    projectId: 'sgpjtjcn-65e0a',
    storageBucket: 'sgpjtjcn-65e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9Ew_u3NeCqPNOqlc2CAjrMeSTZnu_nE',
    appId: '1:1001314955992:ios:9959f68cbca0386e881dad',
    messagingSenderId: '1001314955992',
    projectId: 'sgpjtjcn-65e0a',
    storageBucket: 'sgpjtjcn-65e0a.appspot.com',
    iosClientId: '1001314955992-o1st80q13dds8aoi66jrihg6msk3akjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgpjtjcn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm9Ew_u3NeCqPNOqlc2CAjrMeSTZnu_nE',
    appId: '1:1001314955992:ios:9959f68cbca0386e881dad',
    messagingSenderId: '1001314955992',
    projectId: 'sgpjtjcn-65e0a',
    storageBucket: 'sgpjtjcn-65e0a.appspot.com',
    iosClientId: '1001314955992-o1st80q13dds8aoi66jrihg6msk3akjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgpjtjcn',
  );
}
